/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

export const imageShotTypeOptions = [
  { value: "Cinematic Wide Shot", label: "Góc toàn cảnh (Wide Shot)" },
  { value: "Cinematic Medium Shot", label: "Góc trung cảnh (Medium Shot)" },
  { value: "Cinematic Close-up Shot", label: "Góc cận cảnh (Close-up)" },
  { value: "Cinematic Extreme Close-up", label: "Góc đặc tả (Extreme Close-up)" },
  { value: "High-angle Shot", label: "Góc cao (High-angle)" },
  { value: "Low-angle Shot", label: "Góc thấp (Low-angle)" },
  { value: "Dutch Angle Shot", label: "Góc nghiêng (Dutch Angle)" },
  { value: "Point of View (POV) Shot", label: "Góc nhìn chủ quan (POV)" },
  { value: "Over-the-shoulder Shot", label: "Góc qua vai (Over-the-shoulder)" },
  { value: "Drone Shot", label: "Góc flycam (Drone Shot)" },
];

export const cuttingStyleOptions = [
  { value: 'None', label: 'Không sử dụng', description: 'Không áp dụng kỹ thuật cắt cảnh cụ thể.' },
  { value: 'Hard Cut', label: 'Cắt Thẳng (Hard Cut)', description: 'Chuyển cảnh trực tiếp, duy trì nhịp độ.' },
  { value: 'Cutting on Action', label: 'Cắt tại Hành động (Cutting on Action)', description: 'Cắt trong lúc hành động để tạo sự mượt mà.' },
  { value: 'Jump Cut', label: 'Cắt Nhảy (Jump Cut)', description: 'Tua nhanh thời gian, tạo cảm giác gấp gáp.' },
  { value: 'Match Cut', label: 'Cắt Đồng Nhất (Match Cut)', description: 'Liên kết 2 cảnh qua hình ảnh/hành động tương đồng.' },
  { value: 'Cross Cut', label: 'Cắt Chéo/Song Song (Cross Cut)', description: 'Chuyển đổi giữa 2 hành động diễn ra cùng lúc.' },
  { value: 'Cutaway', label: 'Cắt Chèn (Cutaway)', description: 'Chèn một cảnh chi tiết rồi quay lại cảnh chính.' },
  { value: 'Smash Cut', label: 'Cắt Đột Ngột (Smash Cut)', description: 'Tạo cú sốc bằng cách chuyển từ cảnh tĩnh sang động (hoặc ngược lại).' },
];

export const cameraAngleOptions = [
  { value: "None", label: "Không sử dụng" },
  { value: "Bullet Time", label: "Bullet Time – Orbit 360° quanh chủ thể" },
  { value: "Crane Overhead", label: "Crane Overhead – Camera top-down, hạ xuống" },
  { value: "Crane Down", label: "Crane Down – Xuống nhanh từ cao" },
  { value: "Crane Up", label: "Crane Up – Ngẩng từ thấp lên cao" },
  { value: "Crash Zoom In", label: "Crash Zoom In – Zoom cực nhanh vào chủ thể" },
  { value: "Crash Zoom Out", label: "Crash Zoom Out – Zoom nhanh ra ngoài" },
  { value: "Dolly In", label: "Dolly In – Camera tiến về phía nhân vật" },
  { value: "Dolly Out", label: "Dolly Out – Camera lùi xa dần" },
  { value: "Dolly Left", label: "Dolly Left – Trượt ngang trái" },
  { value: "Dolly Right", label: "Dolly Right – Trượt ngang phải" },
  { value: "Orbit Left", label: "Orbit Left – Quay vòng trái quanh chủ thể" },
  { value: "Orbit Right", label: "Orbit Right – Quay vòng phải quanh chủ thể" },
  { value: "Tilt Up", label: "Tilt Up – Nghiêng máy từ dưới lên" },
  { value: "Tilt Down", label: "Tilt Down – Nghiêng máy từ trên xuống" },
  { value: "Super Dolly In", label: "Super Dolly In – Dolly cực dài vào" },
  { value: "Super Dolly Out", label: "Super Dolly Out – Dolly cực dài ra" },
  { value: "Handheld", label: "Handheld – Máy rung tự nhiên" },
  { value: "Lens Crack", label: "Lens Crack – Hiệu ứng ống kính nứt" },
  { value: "Medium Zoom In", label: "Medium Zoom In – Zoom vừa phải" },
  { value: "Eyes In", label: "Eyes In – Đặc tả đôi mắt" },
  { value: "Flood", label: "Flood – Camera quan sát nước tràn" },
  { value: "Exploration", label: "Exploration – Camera di chuyển khám phá" },
  { value: "Disintegration", label: "Disintegration – Nhân vật/cảnh tan biến" },
];

export const cameraAngleToImageShotMap: { [key: string]: string } = {
  "Bullet Time": "360-degree orbital shot, bullet time effect",
  "Crane Overhead": "overhead shot, top-down view, aerial view",
  "Crane Down": "high-angle shot, looking down",
  "Crane Up": "low-angle shot, looking up",
  "Crash Zoom In": "dynamic zoom in, motion blur",
  "Crash Zoom Out": "dynamic zoom out, motion blur",
  "Dolly In": "close-up shot",
  "Dolly Out": "medium shot, subject is further away",
  "Dolly Left": "shot from the side",
  "Dolly Right": "shot from the side",
  "Orbit Left": "orbital shot, view from the side",
  "Orbit Right": "orbital shot, view from the side",
  "Tilt Up": "low-angle shot, tilted upwards",
  "Tilt Down": "high-angle shot, tilted downwards",
  "Super Dolly In": "extreme close-up shot",
  "Super Dolly Out": "wide shot, establishing shot",
  "Handheld": "handheld camera style, slight natural shake",
  "Lens Crack": "cracked lens effect",
  "Medium Zoom In": "medium close-up shot",
  "Eyes In": "extreme close-up on eyes",
  "Flood": "wide shot showing a flooding scene",
  "Exploration": "point-of-view (POV) shot, exploring",
  "Disintegration": "disintegration effect, particles",
};

export const transitionOptions = [
    { value: 'None', label: 'Không sử dụng' },
    { value: 'Hard Cut', label: 'Hard Cut – Cắt thẳng, dứt khoát.' },
    { value: 'Fade In / Fade Out', label: 'Fade In / Fade Out – Mờ dần vào/ra, hoài niệm.' },
    { value: 'Cross Dissolve', label: 'Cross Dissolve – Hòa vào nhau, tình cảm, mơ mộng.' },
    { value: 'Wipe', label: 'Wipe – Cảnh mới trượt qua, phong cách retro.' },
    { value: 'Match Cut', label: 'Match Cut – Hai hình khớp nhau, sáng tạo.' },
    { value: 'Whip Pan', label: 'Whip Pan – Lướt nhanh tạo blur, năng động.' },
    { value: 'Jump Cut', label: 'Jump Cut – Cắt nhảy thời gian, dồn nhịp.' },
    { value: 'Invisible Cut', label: 'Invisible Cut – Cắt giấu sau vật thể, hiệu ứng one-shot.' },
    { value: 'Smash Cut', label: 'Smash Cut – Cắt sốc, từ yên lặng sang hỗn loạn.' },
    { value: 'Sound Bridge', label: 'Sound Bridge – Âm thanh cảnh sau xuất hiện trước, liền mạch.' },
    { value: 'Iris In / Iris Out', label: 'Iris In / Iris Out – Mở/đóng vòng tròn, cổ điển, tập trung.' },
    { value: 'Ripple Dissolve', label: 'Ripple Dissolve – Hiệu ứng gợn sóng, ảo giác, ký ức.' },
    { value: 'Light Leak', label: 'Light Leak – Ánh sáng lọt vào, tạo cảm giác phim cũ, hoài cổ.' },
    { value: 'Glitch', label: 'Glitch – Hiệu ứng nhiễu kỹ thuật số, hiện đại, sci-fi.' },
    { value: 'Zoom Transition', label: 'Zoom Transition – Zoom cực nhanh vào một điểm, chuyển sang cảnh mới.' },
    { value: 'Spin Transition', label: 'Spin Transition – Xoay tròn cảnh, chóng mặt, chuyển động nhanh.' },
    { value: 'Luma Fade', label: 'Luma Fade – Dùng độ sáng để chuyển, mềm mại, nghệ thuật.' },
    { value: 'Mask Transition', label: 'Mask Transition – Dùng hình dạng hoặc vật thể để che và lộ cảnh mới.' },
    { value: 'Split Screen', label: 'Split Screen – Chia màn hình thành nhiều khung, đa góc nhìn.' },
    { value: 'Liquid Dissolve', label: 'Liquid Dissolve – Hiệu ứng chuyển cảnh tan chảy, siêu thực.' }
];

export const skinToneOptions = [
    { value: '#FFF5F2', label: 'Porcelain Pink' },
    { value: '#FBE8E0', label: 'Fair Peach' },
    { value: '#F3E1D7', label: 'Fair Neutral' },
    { value: '#F5E0C9', label: 'Light Warm' },
    { value: '#EBC9A5', label: 'Light Tan' },
    { value: '#D6A77A', label: 'Medium Honey' },
    { value: '#B98057', label: 'Bronze Deep' },
    { value: '#8C5A39', label: 'Rich Mocha' },
    { value: '#FDF5E6', label: 'Pale Ivory' },
    { value: '#E0C19B', label: 'Warm Sand' },
    { value: '#BFA16F', label: 'Golden Olive' },
    { value: '#A67B5B', label: 'Caramel' },
    { value: '#6F4A3E', label: 'Espresso' },
    { value: '#5C3D32', label: 'Mahogany' },
    { value: '#3E2F2E', label: 'Deep Cocoa' },
    { value: '#1F1F1F', label: 'Midnight Black' },
    { value: '#D2B48C', label: 'Cool Beige' },
    { value: '#C7A68C', label: 'Rose Beige' }
];

export const colorPaletteOptions = [
    { value: 'Golden Hour Warmth', label: 'Golden Hour Warmth', colors: ['#FFBF69', '#FF6B35', '#FFD6A5', '#B5651D', '#FFE66D'] },
    { value: 'Teal–Orange Cinematic', label: 'Teal–Orange Cinematic', colors: ['#1B4965', '#5FA8D3', '#0D1B2A', '#FF6F00', '#FFD6A5'] },
    { value: 'Pastel Dream', label: 'Pastel Dream', colors: ['#A2D2FF', '#CDB4DB', '#FFC8DD', '#B9FBC0', '#FFFFE0'] },
    { value: 'Mystic Forest', label: 'Mystic Forest', colors: ['#013220', '#6B8E23', '#CFCFCF', '#5C4033', '#F5F5F5'] },
    { value: 'Noir Monochrome', label: 'Noir Monochrome', colors: ['#000000', '#2E2E2E', '#595959', '#B0B0B0', '#FFFFFF'] },
    { value: 'Ethereal Fantasy', label: 'Ethereal Fantasy', colors: ['#89CFF0', '#9D4EDD', '#FF5D8F', '#E9EFFF', '#FFD700'] },
    { value: 'Urban Neon Glow', label: 'Urban Neon Glow', colors: ['#FF2D95', '#00F5FF', '#5A189A', '#00FFFF', '#1A1A1A'] },
    { value: 'Desert Dusk', label: 'Desert Dusk', colors: ['#F4E1D2', '#E07A5F', '#D1495B', '#772E25', '#6A0572'] },
    { value: 'Ocean Serenity', label: 'Ocean Serenity', colors: ['#013A63', '#00B4D8', '#48CAE4', '#EAD2AC', '#F8F9FA'] },
    { value: 'Aurora Borealis Glow', label: 'Aurora Borealis Glow', colors: ['#50C878', '#00FFD1', '#8E44AD', '#FF2E63', '#0F3460'] },
    { value: 'Vintage Sepia', label: 'Vintage Sepia', colors: ['#704214', '#805612', '#966C3E', '#B48C5F', '#D6C29E'] },
    { value: 'Cyberpunk Cityscape', label: 'Cyberpunk Cityscape', colors: ['#00FFFF', '#FF00FF', '#00FF00', '#4B0082', '#2A2A2A'] },
    { value: 'Lush Rainforest', label: 'Lush Rainforest', colors: ['#004C00', '#006400', '#228B22', '#556B2F', '#90EE90'] },
    { value: 'Winter Morning', label: 'Winter Morning', colors: ['#B0C4DE', '#E6E6FA', '#F0F8FF', '#ADD8E6', '#D3D3D3'] },
    { value: 'Suburban Calm', label: 'Suburban Calm', colors: ['#8B4513', '#F5F5DC', '#A0522D', '#C0C0C0', '#808000'] },
    { value: 'Pastel Goth', label: 'Pastel Goth', colors: ['#8A2BE2', '#6A5ACD', '#483D8B', '#C71585', '#F08080'] },
    { value: 'Steampunk Retro', label: 'Steampunk Retro', colors: ['#B87333', '#CD853F', '#A52A2A', '#8B4513', '#D2B48C'] },
    { value: 'Monsoon Blues', label: 'Monsoon Blues', colors: ['#000080', '#191970', '#4682B4', '#6A5ACD', '#0000FF'] },
    { value: 'Sun-bleached Retro', label: 'Sun-bleached Retro', colors: ['#F5DEB3', '#FFD700', '#FFA500', '#FF6347', '#DC143C'] },
    { value: 'Futuristic Lab', label: 'Futuristic Lab', colors: ['#00FFD1', '#00BFFF', '#0000CD', '#4B0082', '#1A1A1A'] }
];